// Generated by gencpp from file planner/get_plan.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_GET_PLAN_H
#define PLANNER_MESSAGE_GET_PLAN_H

#include <ros/service_traits.h>


#include <planner/get_planRequest.h>
#include <planner/get_planResponse.h>


namespace planner
{

struct get_plan
{

typedef get_planRequest Request;
typedef get_planResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_plan
} // namespace planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner::get_plan > {
  static const char* value()
  {
    return "8e144f8dc287d43924a78579fd276bf9";
  }

  static const char* value(const ::planner::get_plan&) { return value(); }
};

template<>
struct DataType< ::planner::get_plan > {
  static const char* value()
  {
    return "planner/get_plan";
  }

  static const char* value(const ::planner::get_plan&) { return value(); }
};


// service_traits::MD5Sum< ::planner::get_planRequest> should match 
// service_traits::MD5Sum< ::planner::get_plan > 
template<>
struct MD5Sum< ::planner::get_planRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner::get_plan >::value();
  }
  static const char* value(const ::planner::get_planRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::get_planRequest> should match 
// service_traits::DataType< ::planner::get_plan > 
template<>
struct DataType< ::planner::get_planRequest>
{
  static const char* value()
  {
    return DataType< ::planner::get_plan >::value();
  }
  static const char* value(const ::planner::get_planRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner::get_planResponse> should match 
// service_traits::MD5Sum< ::planner::get_plan > 
template<>
struct MD5Sum< ::planner::get_planResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner::get_plan >::value();
  }
  static const char* value(const ::planner::get_planResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::get_planResponse> should match 
// service_traits::DataType< ::planner::get_plan > 
template<>
struct DataType< ::planner::get_planResponse>
{
  static const char* value()
  {
    return DataType< ::planner::get_plan >::value();
  }
  static const char* value(const ::planner::get_planResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MESSAGE_GET_PLAN_H
