// Generated by gencpp from file agent/update_goal.msg
// DO NOT EDIT!


#ifndef AGENT_MESSAGE_UPDATE_GOAL_H
#define AGENT_MESSAGE_UPDATE_GOAL_H

#include <ros/service_traits.h>


#include <agent/update_goalRequest.h>
#include <agent/update_goalResponse.h>


namespace agent
{

struct update_goal
{

typedef update_goalRequest Request;
typedef update_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct update_goal
} // namespace agent


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agent::update_goal > {
  static const char* value()
  {
    return "bbbe7a32ed0951b9a5042e2c7ab47bdc";
  }

  static const char* value(const ::agent::update_goal&) { return value(); }
};

template<>
struct DataType< ::agent::update_goal > {
  static const char* value()
  {
    return "agent/update_goal";
  }

  static const char* value(const ::agent::update_goal&) { return value(); }
};


// service_traits::MD5Sum< ::agent::update_goalRequest> should match 
// service_traits::MD5Sum< ::agent::update_goal > 
template<>
struct MD5Sum< ::agent::update_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agent::update_goal >::value();
  }
  static const char* value(const ::agent::update_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agent::update_goalRequest> should match 
// service_traits::DataType< ::agent::update_goal > 
template<>
struct DataType< ::agent::update_goalRequest>
{
  static const char* value()
  {
    return DataType< ::agent::update_goal >::value();
  }
  static const char* value(const ::agent::update_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agent::update_goalResponse> should match 
// service_traits::MD5Sum< ::agent::update_goal > 
template<>
struct MD5Sum< ::agent::update_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agent::update_goal >::value();
  }
  static const char* value(const ::agent::update_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agent::update_goalResponse> should match 
// service_traits::DataType< ::agent::update_goal > 
template<>
struct DataType< ::agent::update_goalResponse>
{
  static const char* value()
  {
    return DataType< ::agent::update_goal >::value();
  }
  static const char* value(const ::agent::update_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGENT_MESSAGE_UPDATE_GOAL_H
